name: Deploy Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build -t fastapi-app .

      - name: Run Docker container
        run: |
          docker run -d -p 8000:8000 fastapi-app

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to EC2 instance
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@13.48.46.95 << 'EOF'
            # Pull the latest Docker image from Docker Hub or rebuild it
            docker pull nuel224/fastapi-app:latest

            # Stop the old container
            docker stop fastapi-app-container || true

            # Remove the old container
            docker rm fastapi-app-container || true

            # Run the new container
            docker run -d -p 8000:8000 --name fastapi-app-container nuel224/fastapi-app:latest

            # Restart Nginx (if needed)
            sudo systemctl restart nginx || true
          EOF
