name: CI - Run Tests

on:
  pull_request:
    branches:
      - main  # This triggers the workflow on pull requests targeting the main branch

jobs:
  test:
    runs-on: ubuntu-latest  # Use the latest version of Ubuntu as the runner

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9  # Install Python 3.9

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m venv venv  # Create a virtual environment
          source venv/bin/activate  # Activate the virtual environment
          pip install -r requirements.txt  # Install the dependencies from your requirements file

      # Step 4: Run tests with pytest
      - name: Run tests
        run: |
          source venv/bin/activate  # Activate virtual environment
          pytest --maxfail=1 --disable-warnings -q  # Run the tests
